# Import Libraries

In [1]:
import pandas as pd
import numpy as np

# Read Data

In [2]:
filename = 'fhv_tripdata_2019-01.csv.gz'

In [3]:
df = pd.read_csv(filename, compression='gzip', low_memory=False)

In [4]:
df

,dispatching_base_num,pickup_datetime,dropOff_datetime,PUlocationID,DOlocationID,SR_Flag,Affiliated_base_number
0,B00001,2019-01-01 00:30:00,2019-01-01 02:51:55,NaN,NaN,NaN,B00001
1,B00001,2019-01-01 00:45:00,2019-01-01 00:54:49,NaN,NaN,NaN,B00001
2,B00001,2019-01-01 00:15:00,2019-01-01 00:54:52,NaN,NaN,NaN,B00001
3,B00008,2019-01-01 00:19:00,2019-01-01 00:39:00,NaN,NaN,NaN,B00008
4,B00008,2019-01-01 00:27:00,2019-01-01 00:37:00,NaN,NaN,NaN,B00008
...,...,...,...,...,...,...,...
23143217,B03157,2019-01-31 23:21:00,2019-01-31 23:28:52,NaN,265.0,NaN,B03157
23143218,B03157,2019-01-31 23:38:04,2019-01-31 23:45:43,NaN,265.0,NaN,B03157
23143219,B03157,2019-01-31 23:53:58,2019-02-01 00:25:04,NaN,265.0,NaN,B03157
23143220,B03157,2019-01-31 23:54:53,2019-02-01 00:00:14,NaN,265.0,NaN,B03157
23143221,B03164,2019-01-31 23:55:47,2019-02-01 00:24:29,NaN,265.0,NaN,B03164

In [5]:
df.columns

Index(['dispatching_base_num', 'pickup_datetime', 'dropOff_datetime',
       'PUlocationID', 'DOlocationID', 'SR_Flag', 'Affiliated_base_number'],
      dtype='object')

# Data and Types Analysis

In [6]:
df.dtypes

dispatching_base_num       object
pickup_datetime            object
dropOff_datetime           object
PUlocationID              float64
DOlocationID              float64
SR_Flag                   float64
Affiliated_base_number     object
dtype: object

## Is there null values?

In [7]:
df.isnull().any()

dispatching_base_num       True
pickup_datetime           False
dropOff_datetime          False
PUlocationID               True
DOlocationID               True
SR_Flag                    True
Affiliated_base_number     True
dtype: bool

## Unique values

In [8]:
df['dispatching_base_num'].unique()
df['dispatching_base_num'].replace('\\N', np.nan,inplace=True)

C:\Users\stb10\AppData\Local\Temp\ipykernel_9100\803975782.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['dispatching_base_num'].replace('\\N', np.nan,inplace=True)

In [9]:
sorted(df['PUlocationID'].unique())

[nan,
 0.0,
 1.0,
 2.0,
 3.0,
 4.0,
 5.0,
 6.0,
 7.0,
 8.0,
 9.0,
 10.0,
 11.0,
 12.0,
 13.0,
 14.0,
 15.0,
 16.0,
 17.0,
 18.0,
 19.0,
 20.0,
 21.0,
 22.0,
 23.0,
 24.0,
 25.0,
 26.0,
 27.0,
 28.0,
 29.0,
 30.0,
 31.0,
 32.0,
 33.0,
 34.0,
 35.0,
 36.0,
 37.0,
 38.0,
 39.0,
 40.0,
 41.0,
 42.0,
 43.0,
 44.0,
 45.0,
 46.0,
 47.0,
 48.0,
 49.0,
 50.0,
 51.0,
 52.0,
 53.0,
 54.0,
 55.0,
 56.0,
 57.0,
 58.0,
 59.0,
 60.0,
 61.0,
 62.0,
 63.0,
 64.0,
 65.0,
 66.0,
 67.0,
 68.0,
 69.0,
 70.0,
 71.0,
 72.0,
 73.0,
 74.0,
 75.0,
 76.0,
 77.0,
 78.0,
 79.0,
 80.0,
 81.0,
 82.0,
 83.0,
 84.0,
 85.0,
 86.0,
 87.0,
 88.0,
 89.0,
 90.0,
 91.0,
 92.0,
 93.0,
 94.0,
 95.0,
 96.0,
 97.0,
 98.0,
 99.0,
 100.0,
 101.0,
 102.0,
 105.0,
 106.0,
 107.0,
 108.0,
 109.0,
 110.0,
 111.0,
 112.0,
 113.0,
 114.0,
 115.0,
 116.0,
 117.0,
 118.0,
 119.0,
 120.0,
 121.0,
 122.0,
 123.0,
 124.0,
 125.0,
 126.0,
 127.0,
 128.0,
 129.0,
 130.0,
 131.0,
 132.0,
 133.0,
 134.0,
 135.0,
 136.0,
 137.0,
 138.0,
 139.0,
 140.0,
 141.0,
 142.0,
 143.0,
 144.0,
 145.0,
 146.0,
 147.0,
 148.0,
 149.0,
 150.0,
 151.0,
 152.0,
 153.0,
 154.0,
 155.0,
 156.0,
 157.0,
 158.0,
 159.0,
 160.0,
 161.0,
 162.0,
 163.0,
 164.0,
 165.0,
 166.0,
 167.0,
 168.0,
 169.0,
 170.0,
 171.0,
 172.0,
 173.0,
 174.0,
 175.0,
 176.0,
 177.0,
 178.0,
 179.0,
 180.0,
 181.0,
 182.0,
 183.0,
 184.0,
 185.0,
 186.0,
 187.0,
 188.0,
 189.0,
 190.0,
 191.0,
 192.0,
 193.0,
 194.0,
 195.0,
 196.0,
 197.0,
 198.0,
 199.0,
 200.0,
 201.0,
 202.0,
 203.0,
 204.0,
 205.0,
 206.0,
 207.0,
 208.0,
 209.0,
 210.0,
 211.0,
 212.0,
 213.0,
 214.0,
 215.0,
 216.0,
 217.0,
 218.0,
 219.0,
 220.0,
 221.0,
 222.0,
 223.0,
 224.0,
 225.0,
 226.0,
 227.0,
 228.0,
 229.0,
 230.0,
 231.0,
 232.0,
 233.0,
 234.0,
 235.0,
 236.0,
 237.0,
 238.0,
 239.0,
 240.0,
 241.0,
 242.0,
 243.0,
 244.0,
 245.0,
 246.0,
 247.0,
 248.0,
 249.0,
 250.0,
 251.0,
 252.0,
 253.0,
 254.0,
 255.0,
 256.0,
 257.0,
 258.0,
 259.0,
 260.0,
 261.0,
 262.0,
 263.0,
 264.0,
 265.0]

In [10]:
sorted(df['DOlocationID'].unique())

[nan,
 0.0,
 1.0,
 2.0,
 3.0,
 4.0,
 5.0,
 6.0,
 7.0,
 8.0,
 9.0,
 10.0,
 11.0,
 12.0,
 13.0,
 14.0,
 15.0,
 16.0,
 17.0,
 18.0,
 19.0,
 20.0,
 21.0,
 22.0,
 23.0,
 24.0,
 25.0,
 26.0,
 27.0,
 28.0,
 29.0,
 30.0,
 31.0,
 32.0,
 33.0,
 34.0,
 35.0,
 36.0,
 37.0,
 38.0,
 39.0,
 40.0,
 41.0,
 42.0,
 43.0,
 44.0,
 45.0,
 46.0,
 47.0,
 48.0,
 49.0,
 50.0,
 51.0,
 52.0,
 53.0,
 54.0,
 55.0,
 56.0,
 57.0,
 58.0,
 59.0,
 60.0,
 61.0,
 62.0,
 63.0,
 64.0,
 65.0,
 66.0,
 67.0,
 68.0,
 69.0,
 70.0,
 71.0,
 72.0,
 73.0,
 74.0,
 75.0,
 76.0,
 77.0,
 78.0,
 79.0,
 80.0,
 81.0,
 82.0,
 83.0,
 84.0,
 85.0,
 86.0,
 87.0,
 88.0,
 89.0,
 90.0,
 91.0,
 92.0,
 93.0,
 94.0,
 95.0,
 96.0,
 97.0,
 98.0,
 99.0,
 100.0,
 101.0,
 102.0,
 104.0,
 105.0,
 106.0,
 107.0,
 108.0,
 109.0,
 110.0,
 111.0,
 112.0,
 113.0,
 114.0,
 115.0,
 116.0,
 117.0,
 118.0,
 119.0,
 120.0,
 121.0,
 122.0,
 123.0,
 124.0,
 125.0,
 126.0,
 127.0,
 128.0,
 129.0,
 130.0,
 131.0,
 132.0,
 133.0,
 134.0,
 135.0,
 136.0,
 137.0,
 138.0,
 139.0,
 140.0,
 141.0,
 142.0,
 143.0,
 144.0,
 145.0,
 146.0,
 147.0,
 148.0,
 149.0,
 150.0,
 151.0,
 152.0,
 153.0,
 154.0,
 155.0,
 156.0,
 157.0,
 158.0,
 159.0,
 160.0,
 161.0,
 162.0,
 163.0,
 164.0,
 165.0,
 166.0,
 167.0,
 168.0,
 169.0,
 170.0,
 171.0,
 172.0,
 173.0,
 174.0,
 175.0,
 176.0,
 177.0,
 178.0,
 179.0,
 180.0,
 181.0,
 182.0,
 183.0,
 184.0,
 185.0,
 186.0,
 187.0,
 188.0,
 189.0,
 190.0,
 191.0,
 192.0,
 193.0,
 194.0,
 195.0,
 196.0,
 197.0,
 198.0,
 199.0,
 200.0,
 201.0,
 202.0,
 203.0,
 204.0,
 205.0,
 206.0,
 207.0,
 208.0,
 209.0,
 210.0,
 211.0,
 212.0,
 213.0,
 214.0,
 215.0,
 216.0,
 217.0,
 218.0,
 219.0,
 220.0,
 221.0,
 222.0,
 223.0,
 224.0,
 225.0,
 226.0,
 227.0,
 228.0,
 229.0,
 230.0,
 231.0,
 232.0,
 233.0,
 234.0,
 235.0,
 236.0,
 237.0,
 238.0,
 239.0,
 240.0,
 241.0,
 242.0,
 243.0,
 244.0,
 245.0,
 246.0,
 247.0,
 248.0,
 249.0,
 250.0,
 251.0,
 252.0,
 253.0,
 254.0,
 255.0,
 256.0,
 257.0,
 258.0,
 259.0,
 260.0,
 261.0,
 262.0,
 263.0,
 264.0,
 265.0]

In [11]:
sorted(df['SR_Flag'].unique())

[nan,
 1.0,
 2.0,
 3.0,
 4.0,
 5.0,
 6.0,
 7.0,
 8.0,
 9.0,
 10.0,
 11.0,
 12.0,
 13.0,
 14.0,
 15.0,
 16.0,
 17.0,
 18.0,
 19.0,
 20.0,
 21.0,
 22.0,
 23.0,
 24.0,
 25.0,
 26.0,
 27.0,
 28.0,
 29.0,
 30.0,
 31.0,
 32.0,
 33.0,
 34.0,
 35.0,
 36.0,
 37.0,
 38.0,
 39.0,
 40.0,
 41.0,
 42.0,
 43.0]

In [12]:
list(df['Affiliated_base_number'].unique())
df['Affiliated_base_number'].replace('\s+', '',regex=True,inplace=True)
list(df['Affiliated_base_number'].unique())

C:\Users\stb10\AppData\Local\Temp\ipykernel_9100\3922238019.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Affiliated_base_number'].replace('\s+', '',regex=True,inplace=True)

['B00001',
 'B00008',
 'B00009',
 'B00013',
 'B00037',
 'B02113',
 'B00053',
 'B02520',
 'B02835',
 'B00056',
 'B00111',
 'B00112',
 'B00131',
 'B00149',
 'B00160',
 'B00221',
 'B00225',
 'B00227',
 'B00248',
 'B02356',
 'B00254',
 'B02882',
 'B02994',
 'B00256',
 'B00272',
 'B00280',
 'B00310',
 'B00318',
 'B00346',
 'B00350',
 'B00445',
 'B00446',
 'B00448',
 'B02382',
 'B00457',
 'B00459',
 'B00472',
 'B00477',
 'B00536',
 'B03146',
 'B00608',
 'B00619',
 'B60019',
 'B00628',
 'B02884',
 'B00647',
 'B00652',
 'B00693',
 'B00706',
 'B00756',
 'B02682',
 'B00789',
 'B01469',
 'B00821',
 'B01553',
 'B02674',
 'B02207',
 'B02213',
 'B02879',
 'B02138',
 'B00837',
 'B02788',
 'B01949',
 'B02765',
 'B00856',
 'B02844',
 'B02875',
 'B02764',
 'B02864',
 'B02866',
 'B02878',
 'B02871',
 'B00860',
 'BOO882',
 'B00887',
 'B02465',
 'B02390',
 'B00889',
 'B00900',
 'B00911',
 'B00919',
 'B00932',
 'B00937',
 'B00965',
 'B00972',
 'B00975',
 'B00990',
 'B01048',
 'B01051',
 'B01061',
 'B01065',
 'B01066',
 'B01069',
 'B01079',
 'B01087',
 'B01998',
 'B01129',
 'B01145',
 'B01146',
 'B01148',
 'B01176',
 'B01196',
 'B01200',
 'B02918',
 'B01233',
 'B02867',
 'B01239',
 'B02877',
 'B00882',
 'B02883',
 'B02870',
 'B02711',
 'B02876',
 'B02800',
 'B02872',
 'B01259',
 'B01263',
 'B01285',
 'B01300',
 'B01308',
 'B01315',
 'B01318',
 'B01332',
 'B01336',
 'B01338',
 'B01339',
 'B01340',
 'B01341',
 'B01349',
 'B01362',
 'B01392',
 'B01398',
 'B02990',
 'B02747',
 'B01406',
 'B02888',
 'B01413',
 'B01436',
 'B01437',
 'B01444',
 'B01445',
 'B01452',
 'B01455',
 'B01482',
 'B01485',
 'B01509',
 'B01510',
 'B01522',
 'B01527',
 'B01529',
 'B01540',
 'B01546',
 'B01559',
 'B01593',
 'B01600',
 'B01601',
 'B01606',
 'B01626',
 'B01639',
 'B01663',
 'B01667',
 'B01717',
 'B01721',
 'B01726',
 'B02096',
 'B02376',
 'B02889',
 'B01738',
 'B01742',
 'B01768',
 'B01777',
 'B01800',
 'B01801',
 'B01803',
 nan,
 'B02836',
 'B00306',
 'B01913',
 'B02715',
 'B01958',
 'B03110',
 'B01963',
 'B01979',
 'B01984',
 'B01985',
 'B01995',
 'B02003',
 'B02004',
 'B02021',
 'B02050',
 'B02058',
 'B03065',
 'B02067',
 'B02093',
 'B02099',
 'B02101',
 'B02107',
 'B02111',
 'B02120',
 'B02133',
 'B02145',
 'B02157',
 'B02245',
 'B02249',
 'B02253',
 'B02279',
 'B02285',
 'B02311',
 'B02315',
 'B02330',
 'B02352',
 'B02346',
 'B02681',
 'B02869',
 'B03027',
 'B01010',
 'B01848',
 'B02774',
 'B02183',
 'B02657',
 'B02531',
 'B02660',
 'B02437',
 'B00485',
 'B01614',
 'B02512',
 'B02089',
 'B01536',
 'B02219',
 'B00375',
 'B01811',
 'B01091',
 'B02759',
 'B03035',
 'B02537',
 'B01215',
 'B02562',
 'B02671',
 'B03036',
 'B01313',
 'B02932',
 'B02887',
 'B00948',
 'B02919',
 'B00987',
 'B02782',
 'B02880',
 'B02937',
 'B00271',
 'B03060',
 'B02569',
 'B01056',
 'B03151',
 'B02288',
 'B01743',
 'B02379',
 'B01764',
 'B01194',
 'B02395',
 'B02398',
 'B02401',
 'B02424',
 'B02429',
 'B02461',
 'B02463',
 'B02472',
 'B02505',
 'B00014',
 '5717914',
 'B02617',
 '1905060',
 'b02835',
 'B01678',
 'BLACKCAR',
 'B02492',
 'b02879',
 'B02865',
 '5N1AT2MV7FC753623',
 'B02949',
 'b02864',
 'b02682',
 'b02836',
 'b02765',
 'b02871',
 'b02882',
 'b02888',
 'b02872',
 'B02921',
 'B02896',
 'b02870',
 'B00888',
 'B00296',
 'B03018',
 'B02907',
 'b02869',
 'b02800',
 'B02914',
 'B02638',
 'B02510',
 'b02617',
 'B02342',
 'B02847',
 '5825734',
 'b02788',
 'B02669',
 'B02768',
 'B02860',
 'b02875',
 'B02978',
 'b02867',
 'B02822',
 'B03140',
 '719195',
 'B02902',
 'b02844',
 'B03088',
 'B02908',
 'B02303',
 'b02764',
 'b02866',
 'B02507',
 'B03050',
 'B03136',
 'B03119',
 'b02877',
 'B02846',
 'UBER-ZWEI-NYLLC',
 'B02534',
 '592212',
 'b02887',
 'B02687',
 'B02532',
 '5898280',
 'UBER-VIER-NYC-LLC',
 'B02453',
 'b02884',
 'B028722',
 'B02723',
 'B03029',
 'B02651',
 '450201187',
 '239159',
 'ACHTZEHN',
 'B02960',
 'B02886',
 'B03115',
 'B02863',
 'B02686',
 'Bo2875',
 'B03152',
 'b02880',
 'B03075',
 'B03016',
 'T775662C',
 'B03125',
 'B00381',
 'B01183',
 'b02749',
 'B00411',
 '1556370',
 'R086470',
 'b02865',
 'b02883',
 'B00277',
 'B03141',
 'B02834',
 '11411275',
 'b01949',
 'B02996',
 'B02787',
 'B00202',
 'b02889',
 'b02876',
 'T657417C',
 '576319',
 'B02331',
 'b02878',
 'B02506',
 'B02749',
 '1234',
 'B03167',
 'HC356790',
 'B02905',
 'B01964',
 'B03102',
 '8/10/2018',
 'B02720',
 'Lyft',
 'B08844',
 'b03036',
 '547995',
 'B01871',
 'B02160',
 'B03056',
 'B02550',
 'b02902',
 'B03117',
 'T660365C',
 'b03035',
 'T778190C',
 'UBER-WEITER',
 'T776007C',
 'b02969',
 'B03038',
 '7B02876',
 '5896024',
 'B03002',
 '15169462163',
 'B03049',
 'b02847',
 'B03142',
 'B02753',
 'B02925',
 '6132018',
 't782026c',
 'b03136',
 'B03048',
 'B02984',
 'B01957',
 'B03158',
 'T782928C',
 '5874103',
 'N024144',
 'B02377',
 't717317c',
 'B00235',
 'B02966',
 'B02277',
 'B03074',
 'B02496',
 'B02915',
 'B02148',
 'B02599',
 'B02468',
 'B01877',
 'B03082',
 'B03010',
 'B02480',
 'B02298',
 'B02897',
 'B02536',
 'B02553',
 'B02634',
 'B02653',
 'B02677',
 'B03063',
 'B02688',
 'B02719',
 'B03016+',
 'B02735',
 'B02762',
 'B02373',
 'B01197',
 'B01367',
 'B01875',
 'B03094',
 'B03165',
 'B03168',
 'B00412',
 'B02917',
 'B02806',
 'B02970',
 'B03007',
 'B03096',
 'B02892',
 'B02997',
 'B03153',
 'B02856',
 'B01944',
 'B02240',
 'B03070',
 'B01928',
 'B02732',
 'B02729',
 'B02944',
 'B02256',
 'B02981',
 'B02977',
 'B02817',
 'B03028',
 'B02725',
 'B03109',
 'B01899',
 'B03135',
 'B02814',
 'B03101',
 'B02551',
 'B02898',
 'B02930',
 'B02969',
 'B02664',
 'B02953',
 'B03150',
 'B01309',
 'B03040',
 'B02959',
 'B02611',
 'B02772',
 'B03020',
 'B03126',
 'B03108',
 'B03114',
 'B02868',
 'B03107',
 'B02849',
 'B03017',
 'B02770',
 'B02853',
 'B03014',
 'B03162',
 'B02924',
 'B02469',
 'B02881',
 'B02110',
 'B03080',
 'B03083',
 'B03051',
 'B03166',
 'B02784',
 'B03159',
 'B03185',
 'B02563',
 'B02967',
 'B02518',
 'B03176',
 'B02975',
 'B03127',
 'B03163',
 'B03111',
 'B02971',
 'B03044',
 'B03179',
 'B02588',
 'B01779',
 'B02054',
 'B02825',
 'B03089',
 'B00345',
 'B02855',
 'B03069',
 'B03129',
 'B02916',
 'B02790',
 'B01467',
 'B03073',
 'B02899',
 'B02912',
 'B02942',
 'B03008',
 'B02815',
 'B02699',
 'B02386',
 'B02963',
 'B03086',
 'B02659',
 'B02857',
 'B03041',
 'B03046',
 'B03113',
 'B03157',
 'B03177',
 'b00833',
 'B01016',
 'B01280',
 'B01326',
 'B01466',
 'B01623',
 'B01644',
 'B01700',
 'B01907',
 'B01938',
 'B02060',
 'B02163',
 'B01734',
 'B02546',
 'B02404',
 'T719430C',
 '5602281',
 'B03186',
 'Uber',
 'T715622C',
 '582886',
 'B02826',
 'L90637',
 'UBEE-ELF-NY',
 '5721118',
 'b02404',
 'T779535C',
 'B02939',
 '5776096',
 '906322',
 'B01083',
 '5819555',
 '314380',
 '08/22/2018',
 '5746478',
 '5923166',
 'B02155',
 'B02933',
 'B02440',
 'B02339',
 'B02986',
 'B02217',
 'B02574',
 'B02968',
 'B03055',
 'B02724',
 'B02931',
 'B02976',
 'B02517',
 'B02132',
 'B03122',
 'B02670',
 'B02998',
 'B02989',
 'B03032',
 'B02951',
 'B02552',
 'B03098',
 'B03123',
 'B02408',
 'B02769',
 'B02334',
 'B02022',
 'B02623',
 'B02678',
 'B02016',
 'B03025',
 'B02901',
 'B01912',
 'B02565',
 'B02362',
 'B02667',
 'B00290',
 'B02613',
 'B01980',
 'B01282',
 'B01306',
 'B01039',
 'b02932',
 '8212018',
 '031471',
 '5717018',
 '7112629',
 'B03878',
 'R053494',
 'B03116',
 'BO2765',
 'b02379',
 '9114692',
 '39STINSPECTION',
 'R034177',
 'B00623',
 'B02655',
 'B02761',
 'B03172',
 'B03093',
 'B03021',
 'B03015',
 'B02954',
 'B02533',
 'B03076',
 'B02557',
 'B00881',
 'B01391',
 'B01506',
 'B01625',
 'B01745',
 'B02406',
 '5586339',
 '5784569',
 '5901782',
 'T732179C',
 'B02840',
 '7094533',
 'B02854',
 'UBER-ZWOLF-NY',
 'b00277',
 'B02911',
 'B02956',
 'B02794',
 'B02819',
 'B02799',
 'B02913',
 'B02824',
 'B02903',
 'B03062',
 'B03100',
 'B00337',
 'B00429',
 'B00492',
 'B00802',
 'B01250',
 'B02027',
 'B02254',
 'B02360',
 'B00653',
 '12192018',
 'Q053788',
 'B2678',
 'hc603254',
 'b03063',
 'T719071C',
 'B02947',
 'B02818',
 'B02894',
 'B3040',
 'B00095',
 'B00196',
 'B00210',
 'B01868',
 'B00906',
 'B00991',
 'B01236',
 'B02080',
 'B01808',
 'B02011',
 'B02095',
 'B02391',
 'B02426',
 '12/19/2018',
 '5925752',
 'UBER-VIERZEHN',
 'b02492',
 'P011561',
 '5898919',
 'b03127',
 'B03095',
 'B00281',
 'B00449',
 'B00727',
 'b00855',
 'B01045',
 'B01381',
 'B01534',
 'B02152',
 'B02573',
 'B02641',
 'B02737',
 'B02756',
 'B03118',
 'B02795',
 'B02839',
 'B03033',
 'B02675',
 'B02292',
 'B03059',
 'B00021',
 'B01990',
 'B00827',
 'B01124',
 'B01269',
 'B01312',
 'B01351',
 'B01616',
 'B02055',
 'B02287',
 'B02320',
 'B02471',
 '12/13/2018',
 'b02863',
 'B03137',
 'B03072',
 'B02823',
 'B02934',
 'B02704',
 'B03147',
 'B00531',
 'B01672',
 'B01327',
 'B01417',
 'B01711',
 'B01804',
 'B01821',
 'B01288',
 'B01525',
 'B00385',
 'b02376',
 'B02728',
 'B02736',
 'B03061',
 'B02547',
 'B02811',
 'B03105',
 'B00031',
 'B00556',
 'B00955',
 'B01432',
 'B01568',
 'B02200',
 'B02293',
 'B01109',
 'B01231',
 'B020448',
 'b02886',
 '7107490',
 'B02962',
 'B03052',
 'B02457',
 'B03164',
 'B01424',
 'B02008',
 'b03050',
 'UBER-WEITERLLC',
 'B03047',
 'B03174',
 'B02554',
 'B02566',
 'B02717',
 'B02965',
 'B02833',
 'B03023',
 'B03034',
 'B00387',
 'B02280',
 'B01013',
 'B01854',
 'B00833',
 'B02462',
 '5473075',
 'B02972',
 '12336697',
 'B02306',
 '706675',
 'B02992',
 'B03130',
 'B02418',
 'B02147',
 'B02809',
 'B02243',
 'B00030',
 'B00325',
 'B00419',
 'B01244',
 'B01386',
 'B02144',
 'B02470',
 'B02252',
 'T721685C',
 'B01989',
 'B02594',
 'B03156',
 'B02988',
 'B03024',
 'B00208',
 'B00222',
 'B02980',
 'B01364',
 'B02248',
 'B03124',
 'b02395',
 '1790329',
 'B02284',
 'B02695',
 'B03112',
 'B02926',
 'B03144',
 'B03022',
 'B02943',
 'b01568',
 'B02005',
 'LE2LX-387',
 'B03057',
 'T696154C',
 'T7765151C',
 'b02518',
 'B02684',
 'T779096C',
 'B02515',
 'B02731',
 'B01492',
 'B02301',
 'B03001',
 '09/29/2020',
 '5750911',
 'R018751',
 'B02535',
 'B01970',
 'B00084',
 'B03012',
 'B03131',
 'B03181',
 'B02873',
 'B01674',
 'B02127',
 'UBER-GRUNLLC',
 '286543',
 'T781059C',
 '12/5/2018',
 'B02597',
 'B02627',
 'B80100',
 'B02739',
 'B02841',
 'B02167',
 'b02907',
 'B02830',
 'T7282008C',
 'B03071',
 'B02542',
 'B00039',
 'B02180',
 'B02184',
 'B00625',
 'B02760',
 'BO2871',
 '5631713',
 'B2902',
 'B0003',
 'newyorkcity',
 '5902838',
 'B03058',
 '10923989',
 'B02103',
 'b02729',
 'b02550',
 'BkL8',
 'UBER-ZWEI-NY',
 '5892844',
 '5904723',
 'T758699C',
 '08/28/2018',
 'T776243C',
 '5861442',
 '5890087',
 'B03085',
 'B01470',
 '5819499',
 'b00692',
 'B03031',
 'T777174C',
 'b03027',
 'B02909',
 'uber-grunllc',
 'B00811',
 'BX-375',
 'R160249',
 'B03106',
 'B03171',
 'B02783',
 'B01629',
 'B01710',
 'LE2BX-006',
 'B01741',
 'b02747',
 'B02709',
 'B02803',
 'B02920',
 'B00823',
 'B01653',
 'B01876',
 'B02182',
 'LX-425',
 'B02389',
 'B02397',
 'b02881',
 '080856',
 'T779690C',
 'B03084',
 'B02852',
 'B00255',
 'B01009',
 'B01029',
 'B02335',
 'BK-781',
 'B01751',
 'LE1LX-287',
 'LE2LX-888',
 'LE2LX-012',
 'LE1LX-346',
 'LE7LX-153',
 'B02355',
 'B03009',
 'B02410',
 '11/5/2020',
 'b00256',
 'TYRKMEN',
 'b00937',
 'b03140',
 'B03134',
 'B02797',
 'b02868',
 'B03053',
 'B00559',
 'B00597',
 '6B0062',
 'B01057',
 'B01081',
 'BK-084',
 'LE1BK-244',
 'B01479',
 'LE2BX-123',
 'LE7BX-777',
 'LE3LX-122',
 'LX-795',
 'LE2LX-042',
 'LE1LX-318',
 'LE1LX-392',
 'LE3LX-094',
 'LE1LX-437',
 ...]

## Replace Null values

In [13]:
df[['PUlocationID', 
'DOlocationID', 
'SR_Flag', 
'Affiliated_base_number']].fillna(np.nan, inplace=True)

C:\Users\stb10\AppData\Local\Temp\ipykernel_9100\1504228290.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[['PUlocationID',

## Correct Data Types

In [14]:
df['dispatching_base_num'] = df['dispatching_base_num'].astype('string')
df['PUlocationID'] = df['PUlocationID'].astype('Int64')
df['DOlocationID'] = df['DOlocationID'].astype('Int64')
df['SR_Flag'] = df['SR_Flag'].astype('Int64')
df['Affiliated_base_number'] = df['Affiliated_base_number'].astype('string')

# df.astype({
#             'dispatching_base_num': str,
#             'PUlocationID': int,
#             'DOlocationID': int, 
#             'SR_Flag': int, 
#             'Affiliated_base_number': str
#             }, errors='ignore')

## Datetime transformation

In [15]:
df['pickup_datetime'] = pd.to_datetime(df['pickup_datetime'], format="%Y-%m-%d %H:%M:%S")

In [16]:
df['dropOff_datetime'] = pd.to_datetime(df['dropOff_datetime'], format="%Y-%m-%d %H:%M:%S")

# Correction Analysis

In [17]:
df

,dispatching_base_num,pickup_datetime,dropOff_datetime,PUlocationID,DOlocationID,SR_Flag,Affiliated_base_number
0,B00001,2019-01-01 00:30:00,2019-01-01 02:51:55,<NA>,<NA>,<NA>,B00001
1,B00001,2019-01-01 00:45:00,2019-01-01 00:54:49,<NA>,<NA>,<NA>,B00001
2,B00001,2019-01-01 00:15:00,2019-01-01 00:54:52,<NA>,<NA>,<NA>,B00001
3,B00008,2019-01-01 00:19:00,2019-01-01 00:39:00,<NA>,<NA>,<NA>,B00008
4,B00008,2019-01-01 00:27:00,2019-01-01 00:37:00,<NA>,<NA>,<NA>,B00008
...,...,...,...,...,...,...,...
23143217,B03157,2019-01-31 23:21:00,2019-01-31 23:28:52,<NA>,265,<NA>,B03157
23143218,B03157,2019-01-31 23:38:04,2019-01-31 23:45:43,<NA>,265,<NA>,B03157
23143219,B03157,2019-01-31 23:53:58,2019-02-01 00:25:04,<NA>,265,<NA>,B03157
23143220,B03157,2019-01-31 23:54:53,2019-02-01 00:00:14,<NA>,265,<NA>,B03157
23143221,B03164,2019-01-31 23:55:47,2019-02-01 00:24:29,<NA>,265,<NA>,B03164

In [18]:
df.dtypes

dispatching_base_num      string[python]
pickup_datetime           datetime64[ns]
dropOff_datetime          datetime64[ns]
PUlocationID                       Int64
DOlocationID                       Int64
SR_Flag                            Int64
Affiliated_base_number    string[python]
dtype: object

# Store as Parquet

In [25]:
file_name = filename.replace('.csv.gz', '.parquet')

In [20]:
df.to_parquet(file_name, engine='pyarrow')

# Retrieve from parquet

In [26]:
df = pd.read_parquet(file_name, engine='pyarrow')

In [27]:
df

,dispatching_base_num,pickup_datetime,dropOff_datetime,PUlocationID,DOlocationID,SR_Flag,Affiliated_base_number
0,B00001,2019-01-01 00:30:00,2019-01-01 02:51:55,NaN,NaN,NaN,B00001
1,B00001,2019-01-01 00:45:00,2019-01-01 00:54:49,NaN,NaN,NaN,B00001
2,B00001,2019-01-01 00:15:00,2019-01-01 00:54:52,NaN,NaN,NaN,B00001
3,B00008,2019-01-01 00:19:00,2019-01-01 00:39:00,NaN,NaN,NaN,B00008
4,B00008,2019-01-01 00:27:00,2019-01-01 00:37:00,NaN,NaN,NaN,B00008
...,...,...,...,...,...,...,...
23143217,B03157,2019-01-31 23:21:00,2019-01-31 23:28:52,NaN,265.0,NaN,B03157
23143218,B03157,2019-01-31 23:38:04,2019-01-31 23:45:43,NaN,265.0,NaN,B03157
23143219,B03157,2019-01-31 23:53:58,2019-02-01 00:25:04,NaN,265.0,NaN,B03157
23143220,B03157,2019-01-31 23:54:53,2019-02-01 00:00:14,NaN,265.0,NaN,B03157
23143221,B03164,2019-01-31 23:55:47,2019-02-01 00:24:29,NaN,265.0,NaN,B03164

In [28]:
df.dtypes

dispatching_base_num              object
pickup_datetime           datetime64[ns]
dropOff_datetime          datetime64[ns]
PUlocationID                     float64
DOlocationID                     float64
SR_Flag                          float64
Affiliated_base_number            object
dtype: object